### ISSUE TITLE
Add binary release

### ISSUE THREAD

**Issue by berendt** [greenpau/ovs_exporter#2]
It would make sense to have the binary artifact directly in the release.

**Comment by greenpau** [comment]
@berendt , I am adding Github Actions and will build an artifact there.

**Comment by berendt** [comment]
@greenpau Great. Thank you for the quick implementation.

**Comment by greenpau** [comment]
@berendt , also, wouldn't it be easier to do the following?

```
go get -u github.com/greenpau/ovs_exporter/cmd/ovs_exporter
```

**Comment by berendt** [comment]
@greenpau I would like to use the binary in Kolla for a new image. There we pull the tarballs of the exporters by curl from Github. From our point of view it would be good if we could make it uniform there.

https://github.com/openstack/kolla/blob/master/docker/prometheus/prometheus-memcached-exporter/Dockerfile.j2#L13

Edit: https://review.opendev.org/c/openstack/kolla/+/764995

**Comment by greenpau** [comment]
> From our point of view it would be good if we could make it uniform there.

@berendt , understood. Will get the binary done. Also, I wrote this exporter a while ago. Unfortunately, I switched a job to one where I do not use my cloud skills. Does the exporter still work? :-) ... btw, if you hear people hiring in NYC, please ping me.

**Comment by greenpau** [comment]
@berendt , all done.

![image](https://user-images.githubusercontent.com/3826416/100792789-2f5db900-33e9-11eb-9b10-41701ac46cdf.png)

Please test and close the issue if all is well.

**Comment by greenpau** [comment]
@berendt , I just checked and the exporter is working.

**Comment by greenpau** [comment]
@berendt , i improved tests. Please see Run stage of the latest Github Actions run. It has the metrics the exporter exports.

**Comment by berendt** [comment]
Thank you. Can you please add arm64 as 2nd architecture?

I'm testing the image today and then giving feedback again.

**Comment by greenpau** [comment]
> Thank you. Can you please add arm64 as 2nd architecture?

@berendt , done.

![image](https://user-images.githubusercontent.com/3826416/100897303-8ddc7300-348d-11eb-9629-ddb572612a1a.png)
